// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCd3a1cln4AdPRyAxytg23-SQi3hVXqPk',
    appId: '1:625706484694:web:8b998b056e7a2e1b241a77',
    messagingSenderId: '625706484694',
    projectId: 'vibelink-10a34',
    authDomain: 'vibelink-10a34.firebaseapp.com',
    storageBucket: 'vibelink-10a34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRn8YSWRW-cye5e2D7T8GlsJ2-BdPFrw',
    appId: '1:625706484694:android:ee7c0b0b1a61f1d9241a77',
    messagingSenderId: '625706484694',
    projectId: 'vibelink-10a34',
    storageBucket: 'vibelink-10a34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVhVVZkxzSZD12eY_vtLUoG9-boc2Y58',
    appId: '1:625706484694:ios:f0b385a96a75339f241a77',
    messagingSenderId: '625706484694',
    projectId: 'vibelink-10a34',
    storageBucket: 'vibelink-10a34.firebasestorage.app',
    androidClientId: '625706484694-5av174m5oevf6rn30goq32bmvakmoigr.apps.googleusercontent.com',
    iosClientId: '625706484694-kccp4o60uee1hfak89fphhr3ocua6gag.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeLink',
  );

}